SYS_TARGET_PROJECT := mssi_32_ww_armv7
SYS_TARGET_PROJECT_FOLDER := device/mediatek/system/$(SYS_TARGET_PROJECT)
MTK_TARGET_PROJECT := X5
MTK_TARGET_PROJECT_FOLDER := $(LOCAL_PATH)

include $(SYS_TARGET_PROJECT_FOLDER)/sys_$(SYS_TARGET_PROJECT).mk

include device/DOOGEE/X5/vnd_$(MTK_TARGET_PROJECT).mk

PRODUCT_NAME := full_X5

